### ISSUE TITLE
Array.toString() doesn’t quote strings

### ISSUE THREAD

**Issue by FGasper** [near/assemblyscript-json#227]
```
    var jsonarray = JSON.Value.Array();

    var thearray = _validate_ipv4(str);

    for (var i=0; i<thearray.length; i++) {
        var thisstr = JSON.Value.String(thearray[i]);
        jsonarray.push(thisstr);
    }

    return jsonarray.toString();
```
This is yielding things like: `[leadingZeroes,3]`, which of course isn’t valid.

It looks like the writeString() from the Object writer just needs to be accessible inside the Array writer as well?

**Comment by willemneal** [comment]
Thanks! This line seems to be the issue: 

https://github.com/nearprotocol/assemblyscript-json/pull/121/commits/9be1b2e67eb2b536f0ee34db0b89b18e321ac2f0#diff-49b560e1b5841d25b3cbb84fbc166d03f789b5c6d5ac5fe5f98aed07be9e1f30L204
